/**
 * The live audit's data layer.
 *
 * Two ways in, and the order matters: the bundled fixture is the default and
 * the network is the upgrade. The page has a hard offline requirement — it has
 * to open from a laptop with no connection — so a section that needed a server
 * to have content would break the one delivery promise the build makes.
 *
 * So the fixture is imported, not fetched. It ships in the bundle, renders on
 * mount, and is a real audit of a real product: the same assembler, the same
 * grounding check, the same arithmetic as a live run. The only difference is
 * when it was computed.
 */

import type { Cluster, Insight } from './clusters'
import type { Source } from './sources'
/**
 * Trenitalia rather than a SaaS tool, and the choice is not incidental.
 *
 * The bundled fixture is what a reader sees before they have typed anything —
 * it has to be a company they can check against their own experience, because
 * the claim being made is "these are real defects in a real organisation" and
 * an unfamiliar subject makes that unfalsifiable. For an audience in Italy the
 * national railway's app is the strongest available: everyone in the room has
 * used it, the reviews are in Italian, and the lead finding — payments that
 * charge the card and then report an error — is the kind of thing they can
 * confirm or contradict on the spot.
 */
import fixture from './fixtures/trenitalia.json'
import satispay from './fixtures/satispay.json'
import notion from './fixtures/notion.json'
import hfarm from './fixtures/h-farm.json'

export interface AuditMeta {
  productName: string
  /** Items that survived curation and reached the model. */
  volumeTotal: number
  /**
   * Items collected before curation.
   *
   * Shown beside `volumeTotal` because the gap between them is the argument:
   * a tool that collects fourteen hundred items and reports on seven hundred
   * is selecting, and one that reports on all fourteen hundred is not reading
   * them. The number is only persuasive if the reasons are also shown, which
   * is what `dropped` carries.
   */
  itemsRead?: number
  dropped?: { reason: string; count: number }[]
  windowDays: number
  generatedAt: string
  mode: 'live' | 'cached'
  /** What produced the clustering, so the card can attribute it honestly. */
  model: string
}

export interface AuditResult {
  meta: AuditMeta
  sources: Source[]
  clusters: Cluster[]
  insights: Insight[]
}

/** Cast rather than validate: this file is generated by our own build step. */
export const CACHED_AUDIT = fixture as AuditResult

/**
 * Every baked audit, in the bundle, keyed by name.
 *
 * All three ship rather than only the default one, and the reason is the
 * audience. The page is handed round on phones by QR, where there is no run
 * server to reach and never will be — so without this, a visitor can read one
 * audit and type nothing. With it they can name three real companies and get
 * three real audits instantly, on a hosted static page, with no server, no API
 * key and no quota. That is the difference between showing a result and
 * letting someone check one.
 *
 * The honesty is unaffected: each of these was produced by the same pipeline
 * with the same grounding check, and the card stamps itself "Cached run", so
 * nobody is being shown a live search that is not happening. The cost is about
 * eighteen kilobytes of JSON, which is less than one photograph.
 */
const BAKED: Record<string, AuditResult> = {
  trenitalia: fixture as AuditResult,
  'h-farm': hfarm as unknown as AuditResult,
  satispay: satispay as unknown as AuditResult,
  notion: notion as unknown as AuditResult,
}

/** Names the bundle can answer without a network. Order is display order. */
export const BAKED_TARGETS: AuditTarget[] = Object.entries(BAKED).map(([slug, a]) => ({
  slug,
  productName: a.meta.productName,
  volumeTotal: a.meta.volumeTotal,
}))

/**
 * Resolve a typed query against the baked set.
 *
 * Matching is forgiving in the ways a person on a phone is imprecise — case,
 * spacing, punctuation — and strict about everything else. Returning null is
 * the honest answer for a name we have not audited, and the caller says so
 * rather than showing the previous company's card under a new name.
 */
export function lookupBaked(query: string): AuditResult | null {
  const norm = (s: string) => s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '')
  const q = norm(query)
  if (!q) return null
  for (const [slug, audit] of Object.entries(BAKED)) {
    if (norm(slug) === q || norm(audit.meta.productName) === q) return audit
  }
  return null
}

/**
 * Whether this build is allowed to talk to a run server at all.
 *
 * A dev build probes; a production build does not, unless it was explicitly
 * built to. Handling a failed probe would have been enough to keep the page
 * working offline — but "no external requests" then rests on a promise about
 * error handling, and the network panel still shows a failed call that someone
 * will screenshot and ask about. Gating it means the default production build
 * issues no request at all, which is a property you can verify in one look
 * rather than a behaviour you have to trust.
 *
 * Deploying somewhere that does host the API: build with VITE_AUDIT_API=on.
 */
const MAY_PROBE = import.meta.env.DEV || import.meta.env.VITE_AUDIT_API === 'on'

/**
 * Is a run server reachable?
 *
 * Deliberately short-fused. This decides whether a form appears, and a form
 * that takes three seconds to show up reads as a page still loading. If the
 * server is slow enough to miss this window it is too slow to demo against.
 */
export async function probeAuditServer(signal?: AbortSignal): Promise<boolean> {
  if (!MAY_PROBE) return false
  try {
    const timeout = AbortSignal.timeout(1500)
    const res = await fetch('/api/health', {
      signal: signal ? AbortSignal.any([signal, timeout]) : timeout,
    })
    return res.ok
  } catch {
    // Offline, no server, wrong port, blocked — all the same answer, and none
    // of them are worth telling a visitor about. They just get the cached run.
    return false
  }
}

export interface AuditTarget {
  slug: string
  productName: string
  volumeTotal: number
}

/**
 * Products already baked on the server, offered as one-click targets.
 *
 * These answer from cache in milliseconds. Anything else typed into the search
 * bar runs live, which takes seconds — so the distinction is worth surfacing
 * rather than hiding: on stage you reach for a baked one, and you type a
 * stranger's product when someone in the room names it.
 */
export async function fetchTargets(signal?: AbortSignal): Promise<AuditTarget[]> {
  if (!MAY_PROBE) return []
  try {
    const res = await fetch('/api/targets', { signal })
    if (!res.ok) return []
    const body = (await res.json()) as { targets?: AuditTarget[] }
    return body.targets ?? []
  } catch {
    return []
  }
}

export type AuditEvent =
  | { type: 'progress'; message: string }
  | { type: 'result'; result: AuditResult }
  | { type: 'error'; message: string }

/**
 * Runs an audit, yielding progress as it arrives.
 *
 * The server answers newline-delimited JSON rather than one object at the end,
 * because the interesting part of this product is the pipeline and a spinner
 * hides exactly that. Each stage announces itself as it completes: resolving,
 * fetching, clustering, computing. On stage that is the demo; in production it
 * is the difference between "it's thinking" and "it read 500 reviews".
 */
export async function* runAudit(
  product: string,
  signal?: AbortSignal,
): AsyncGenerator<AuditEvent> {
  // The same gate the other two calls carry, and it was missing here.
  //
  // Nothing could reach this in a default build — the search bar that calls it
  // is not rendered — so no request was ever made. But "unreachable because
  // nobody calls it" is a weaker claim than "not in the bundle", and the
  // difference showed: `/api/health` and `/api/targets` were eliminated by the
  // early return in their functions while the string `/api/audit` survived
  // into the shipped JavaScript. On a page whose entire argument is that a
  // path does not exist rather than merely goes unused, the guarantee should
  // be structural. With this, the fetch is dead code and Vite drops it.
  if (!MAY_PROBE) {
    yield { type: 'error', message: 'Live audit is not enabled in this build.' }
    return
  }

  const res = await fetch('/api/audit', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ product }),
    signal,
  })

  if (!res.ok || !res.body) {
    yield { type: 'error', message: `Run failed (HTTP ${res.status})` }
    return
  }

  const reader = res.body.pipeThrough(new TextDecoderStream()).getReader()
  let buffer = ''

  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    buffer += value

    // A chunk boundary can land mid-line, so the tail is held back until a
    // newline proves it complete. Parsing a half-written object here would
    // fail the run on a network hiccup rather than on anything real.
    const lines = buffer.split('\n')
    buffer = lines.pop() ?? ''

    for (const line of lines) {
      if (!line.trim()) continue
      try {
        yield JSON.parse(line) as AuditEvent
      } catch {
        yield { type: 'error', message: 'Malformed response from the audit server' }
        return
      }
    }
  }
}
